vim.g.mapleader = " "
vim.g.maplocalleader = " "

vim.keymap.set("n", "<leader>wsh", "<CMD>leftabove vsplit<CR>")
vim.keymap.set("n", "<leader>wsj", "<CMD>rightbelow split<CR>")
vim.keymap.set("n", "<leader>wsk", "<CMD>leftabove split<CR>")
vim.keymap.set("n", "<leader>wsl", "<CMD>rightbelow vsplit<CR>")
vim.keymap.set("n", "<leader>wnh", "<CMD>leftabove vnew<CR>")
vim.keymap.set("n", "<leader>wnj", "<CMD>rightbelow new<CR>")
vim.keymap.set("n", "<leader>wnk", "<CMD>leftabove new<CR>")
vim.keymap.set("n", "<leader>wnl", "<CMD>rightbelow vnew<CR>")
vim.keymap.set("n", "<leader>wq", "<CMD>quit<CR>")
vim.keymap.set("n", "<leader>wc", "<CMD>close<CR>")
vim.keymap.set("n", "<leader>we", "<CMD>hide<CR>")
vim.keymap.set("n", "<leader>wo", "<CMD>only<CR>")

vim.keymap.set("n", "<C-h>", "<C-w>h")
vim.keymap.set("n", "<C-j>", "<C-w>j")
vim.keymap.set("n", "<C-k>", "<C-w>k")
vim.keymap.set("n", "<C-l>", "<C-w>l")
vim.keymap.set("n", "<leader>wh", "<C-w>h")
vim.keymap.set("n", "<leader>wj", "<C-w>j")
vim.keymap.set("n", "<leader>wk", "<C-w>k")
vim.keymap.set("n", "<leader>wl", "<C-w>l")
vim.keymap.set("n", "<leader>ww", "<C-w>w")
vim.keymap.set("n", "<leader>wt", "<C-w>t")
vim.keymap.set("n", "<leader>wb", "<C-w>b")
vim.keymap.set("n", "<leader>wp", "<C-w>p")
vim.keymap.set("n", "<leader>wP", "<C-w>P")

vim.keymap.set("n", "<leader>wr", "<C-w>r")
vim.keymap.set("n", "<leader>wR", "<C-w>R")
vim.keymap.set("n", "<leader>wx", "<C-w>x")
vim.keymap.set("n", "<leader>wH", "<C-w>H")
vim.keymap.set("n", "<leader>wJ", "<C-w>J")
vim.keymap.set("n", "<leader>wK", "<C-w>K")
vim.keymap.set("n", "<leader>wL", "<C-w>L")
vim.keymap.set("n", "<leader>wT", "<C-w>T")

vim.keymap.set("n", "<C-Up>", ":resize +2<CR>")
vim.keymap.set("n", "<C-Down>", ":resize -2<CR>")
vim.keymap.set("n", "<C-Left>", ":vertical resize -2<CR>")
vim.keymap.set("n", "<C-Right>", ":vertical resize +2<CR>")
vim.keymap.set("n", "<leader>w=", "<C-w>=")
vim.keymap.set("n", "<leader>w+", ":resize +2<CR>")
vim.keymap.set("n", "<leader>w-", ":resize -2<CR>")
vim.keymap.set("n", "<leader>w<", ":vertical resize -2<CR>")
vim.keymap.set("n", "<leader>w>", ":vertical resize +2<CR>")

vim.keymap.set("n", "<Tab>", ":bnext<CR>")
vim.keymap.set("n", "<S-Tab>", ":bprevious<CR>")
vim.keymap.set("n", "<leader>bn", "<CMD>bnext<CR>")
vim.keymap.set("n", "<leader>bp", "<CMD>bprev<CR>")
vim.keymap.set("n", "<leader>bN", "<CMD>blast<CR>")
vim.keymap.set("n", "<leader>bP", "<CMD>bfirst<CR>")
vim.keymap.set("n", "<leader>bx", "<CMD>bdelete<CR>")

vim.keymap.set("v", "p", '"_dP')

vim.keymap.set("v", "<A-j>", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "<A-k>", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "<A-j>", ":m .+1<CR>==")
vim.keymap.set("n", "<A-k>", ":m .-2<CR>==")

vim.keymap.set("v", ">", ">gv")
vim.keymap.set("v", "<", "<gv")

vim.keymap.set("n", "<Esc>", ":nohl<CR>")

vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n", "nzz")
vim.keymap.set("n", "N", "Nzz")
